apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vexa-lite.configmapName" . }}
  labels:
{{ include "vexa-lite.labels" . | nindent 4 }}
data:
  ORCHESTRATOR: {{ .Values.vexa.orchestrator | quote }}
{{ if .Values.vexa.transcriberUrl }}
  TRANSCRIBER_URL: {{ .Values.vexa.transcriberUrl | quote }}
{{ end }}
{{ if .Values.vexa.dbSslMode }}
  DB_SSL_MODE: {{ .Values.vexa.dbSslMode | quote }}
{{ end }}
{{ range $key, $val := .Values.vexa.extraEnv }}
  {{ $key }}: {{ $val | quote }}
{{ end }}
