{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vexa-lite.fullname" . }}
  labels:
{{ include "vexa-lite.labels" . | nindent 4 }}
{{ with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
{{ end }}
spec:
{{ if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
{{ end }}
  rules:
{{ range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
{{ range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "vexa-lite.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
{{ end }}
{{ end }}
{{ with .Values.ingress.tls }}
  tls:
{{ toYaml . | nindent 4 }}
{{ end }}
{{ end }}
