{{- if not .Values.secrets.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vexa.componentName" (list . "secrets") }}
  labels:
    {{- include "vexa.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_API_TOKEN: {{ .Values.secrets.adminApiToken | quote }}
  TRANSCRIBER_API_KEY: {{ .Values.secrets.transcriberApiKey | quote }}
{{- end }}
