{{- if .Values.botManager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vexa.componentName" (list . "bot-manager") }}
  labels:
    {{- include "vexa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.botManager.service.type }}
  ports:
    - name: http
      port: {{ .Values.botManager.service.port }}
      targetPort: http
  selector:
    {{- include "vexa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bot-manager
{{- end }}
