{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vexa.componentName" (list . "postgres") }}
  labels:
    {{- include "vexa.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: pg
      port: {{ .Values.postgres.service.port }}
      targetPort: pg
  selector:
    {{- include "vexa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
