{{- if .Values.whisperLive.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vexa.componentName" (list . "whisperlive") }}
  labels:
    {{- include "vexa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.whisperLive.service.type }}
  ports:
    - name: ws
      port: {{ .Values.whisperLive.service.wsPort }}
      targetPort: ws
    - name: health
      port: {{ .Values.whisperLive.service.healthPort }}
      targetPort: health
  selector:
    {{- include "vexa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: whisperlive
{{- end }}
