{{- if .Values.apiGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vexa.componentName" (list . "api-gateway") }}
  labels:
    {{- include "vexa.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
    - name: http
      port: {{ .Values.apiGateway.service.port }}
      targetPort: http
  selector:
    {{- include "vexa.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
{{- end }}
